import 'package:flutter/material.dart';import 'package:flutter_svg_provider/flutter_svg_provider.dart' as fs;import 'package:try/core/app_export.dart';import 'package:try/core/utils/validation_functions.dart';import 'package:try/widgets/app_bar/appbar_image.dart';import 'package:try/widgets/app_bar/appbar_subtitle_1.dart';import 'package:try/widgets/app_bar/custom_app_bar.dart';import 'package:try/widgets/custom_button.dart';import 'package:try/widgets/custom_text_form_field.dart';
// ignore_for_file: must_be_immutable

// ignore_for_file: must_be_immutable
class AngsuranTwoScreen extends StatelessWidget {TextEditingController customernumberController = TextEditingController();

GlobalKey<FormState> _formKey = GlobalKey<FormState>();

@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(backgroundColor: ColorConstant.whiteA700, resizeToAvoidBottomInset: false, appBar: CustomAppBar(height: getVerticalSize(66), leadingWidth: 52, leading: AppbarImage(height: getSize(30), width: getSize(30), svgPath: ImageConstant.imgArrowleft, margin: getMargin(left: 22, top: 13, bottom: 12), onTap: () => onTapArrowleft70(context)), centerTitle: true, title: AppbarSubtitle1(text: "Angsuran"), styleType: Style.bgFillWhiteA700), body: Form(key: _formKey, child: Container(width: double.maxFinite, child: Column(crossAxisAlignment: CrossAxisAlignment.start, mainAxisAlignment: MainAxisAlignment.start, children: [Padding(padding: getPadding(left: 25, top: 9), child: Text("PT. Angsuran Finance", overflow: TextOverflow.ellipsis, textAlign: TextAlign.left, style: AppStyle.txtPoppinsSemiBold12Gray900)), Padding(padding: getPadding(left: 25, top: 11), child: Text("Nomor Pelanggan", overflow: TextOverflow.ellipsis, textAlign: TextAlign.left, style: AppStyle.txtPoppinsRegular10Gray60001)), CustomTextFormField(focusNode: FocusNode(), controller: customernumberController, hintText: "452217980", margin: getMargin(left: 25, top: 1, right: 25), variant: TextFormFieldVariant.FillTeal50, textInputAction: TextInputAction.done, textInputType: TextInputType.phone, alignment: Alignment.center, suffix: Container(margin: getMargin(left: 30, top: 8, right: 12, bottom: 7), child: CustomImageView(svgPath: ImageConstant.imgClose)), suffixConstraints: BoxConstraints(maxHeight: getVerticalSize(35))), Container(height: getVerticalSize(593), width: double.maxFinite, margin: getMargin(top: 32), child: Stack(alignment: Alignment.bottomCenter, children: [Align(alignment: Alignment.center, child: Container(height: getVerticalSize(590), width: double.maxFinite, decoration: BoxDecoration(color: ColorConstant.gray200))), Align(alignment: Alignment.bottomCenter, child: Container(padding: getPadding(left: 25, top: 11, right: 25, bottom: 11), decoration: BoxDecoration(image: DecorationImage(image: fs.Svg(ImageConstant.imgGroup962), fit: BoxFit.cover)), child: Column(mainAxisSize: MainAxisSize.min, mainAxisAlignment: MainAxisAlignment.center, children: [CustomButton(height: getVerticalSize(37), text: "Lanjut", margin: getMargin(bottom: 1), onTap: () => onTapLanjut(context))])))]))]))))); } 
onTapLanjut(BuildContext context) { Navigator.pushNamed(context, AppRoutes.angsuranOneScreen); } 
onTapArrowleft70(BuildContext context) { Navigator.pop(context); } 
 }
